FROM php:7.0-apache

RUN echo "UTC" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        zlib1g-dev \
        git \
    && docker-php-ext-install -j$(nproc) iconv mcrypt zip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

ADD php.ini $PHP_INI_DIR/conf.d/php.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && /usr/local/bin/composer --repository-url="https://raw.githubusercontent.com/dru-id/druid-php-skel/v1.0.3" --dev create-project druid/php-skel /usr/src/druid \
    && sed -i -- 's/\/var\/www\/html/\/var\/www\/webapp/g' /etc/apache2/sites-enabled/000-default.conf \
    && usermod -u 1000 www-data \
    && usermod -G staff www-data

ADD druid-ini.sh /usr/local/bin

VOLUME /var/www

WORKDIR /var/www

CMD druid-ini.sh
